### ISSUE TITLE
Exception when running GST example

### ISSUE THREAD

**Issue by eendebakpt** [pyGSTio/pyGSTi#223] opened 2022-01-04 10:40 UTC
**Describe the bug**
When I run the example notebook `master/jupyter_notebooks/Tutorials/algorithms/GST-Overview.ipynb` I get the following error:
```
ValueError: Could not interpret 'CPTP' mode as a parameterization! Details:
Could not convert operation to to type(s): ('CPTP',)
```
This is with the notebook and package both from current master branch.

**To Reproduce**
1. Run `GST-Overview.ipynb`
2. See error

**Expected behavior**
The standard example should execute without errors. Also the documentation for the CPTP mode could be improved. Is there somewhere a description why TP and CPTP are the default modes?

**Environment (please complete the following information):**
 - pyGSTi version: 0.9.10.post4
 - python version: 3.8
 - OS: Windows

**Additional context**
Other arguments such as `'S'` give similar errors.

**Comment by enielse** [comment] 2022-01-04 23:36
Could you confirm you're on the tip of the master branch, i.e., commit 4f8bf5337b01b7afcb7b0580b717b5d1fe281be4?  I'm unable to reproduce this using python 3.8 on OSX 10.15 or on Windows 10.

Please also ensure that you've installed pyGSTi after pulling.  You can run `pip install` or `pip install -e .` (to install locally) from the root `pyGSTi/` directory to do this.

**Comment by peendebak** [comment] 2022-01-05 22:33
@enielse I am at the master branch. A minimal example that creates the problem here is:
``` 
import pygsti
from pygsti.modelpacks import smq1Q_XYI

target_model = smq1Q_XYI.target_model()#.depolarize(op_noise=0.00, spam_noise=0.00)      # a Model object
prep_fiducials = smq1Q_XYI.prep_fiducials()  # a list of Circuit objects
meas_fiducials = smq1Q_XYI.meas_fiducials()  # a list of Circuit objects
germs = smq1Q_XYI.germs()                    # a list of Circuit objects
maxLengths = [1,2,4,8,16,32]
exp_design = pygsti.protocols.StandardGSTDesign(target_model, prep_fiducials, meas_fiducials,
                                                germs, maxLengths)

model = exp_design.create_target_model()
model.set_all_parameterizations('CPTP')
```
To check I did a clean install (using `virtualenv`) and the problem still occurs. I did notice a warning though: `Buffer dtype mismatch, expected 'int64_t' but got 'long'` is printed just before the exception occurs.
This is with numpy 1.22. 

If I switch to numpy 1.21 (and to a `pip install .` again) I get this stack trace
```
(py38) c:\projects\misc\pyGSTi>python \data\tmp\test_gst.py
Traceback (most recent call last):
  File "\data\tmp\test_gst.py", line 19, in <module>
    import pygsti
  File "C:\data\py38\lib\site-packages\pygsti\__init__.py", line 11, in <module>
    from . import baseobjs
  File "C:\data\py38\lib\site-packages\pygsti\baseobjs\__init__.py", line 23, in <module>
    from .errorgenbasis import ElementaryErrorgenBasis, ExplicitElementaryErrorgenBasis, CompleteElementaryErrorgenBasis
  File "C:\data\py38\lib\site-packages\pygsti\baseobjs\errorgenbasis.py", line 18, in <module>
    from pygsti.tools import optools as _ot
  File "C:\data\py38\lib\site-packages\pygsti\tools\__init__.py", line 13, in <module>
    from .basistools import *
  File "C:\data\py38\lib\site-packages\pygsti\tools\basistools.py", line 524, in <module>
    from . import matrixtools as _mt
  File "C:\data\py38\lib\site-packages\pygsti\tools\matrixtools.py", line 26, in <module>
    from . import fastcalc as _fastcalc
  File "pygsti\tools\fastcalc.pyx", line 1, in init pygsti.tools.fastcalc
    # encoding: utf-8
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
``` 
Note: with a plain virtualenv environment `cython` is not installed by default. After installing I still get similar errors.

**Comment by peendebak** [comment] 2022-01-06 09:55
@coreyostrove The branch fixes the issue for me. Thanks for looking into this!

**Comment by enielse** [comment] 2022-03-16 16:01
Closing now that version 0.9.10.1 is released.

**Closed by enielse** 2022-03-16 16:01 UTC
Labels: bug, fixed-but-not-in-release-yet
